import Header from '@/components/Header';
import './globals.css';
import ThemeProviders from './ThemeProviders';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProviders>
          <main>
            <Header />
            {children}
          </main>
        </ThemeProviders>
      </body>
    </html>
  );
}
